name: Create diagram
on:
  workflow_dispatch:
    pull_request:
      branches:
        - main
        - develop
    push:
      branches:
        - main
        - develop
        - feature/*

jobs:
  get_data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Update diagram
        uses: githubocto/repo-visualizer@main
        with:
          excluded_paths: "ignore,.github"